In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[2][1]

8

In [5]:
arr[2, 1]

8

In [6]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [7]:
arr2 = arr.copy() > 5

In [8]:
arr2

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr[arr2]

array([6, 7, 8, 9])

In [11]:
arr2[arr2]

array([ True,  True,  True,  True], dtype=bool)

In [15]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
arr = np.arange(0,11)


In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [19]:
arr -100


array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [20]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [21]:
arr / arr

/Users/TimmehK/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [22]:
arr = np.arange(0,11)

In [23]:
1/ arr

/Users/TimmehK/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [24]:
arr = np.arange(0,11)

In [25]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [26]:
arr = np.arange(0,11)

In [27]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [29]:
arr.max()

10